// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZaPj8Vdp1oS_ofEgO8coqjL-DHs4YZZM',
    appId: '1:426460791792:web:b2699ea1c2c33999651335',
    messagingSenderId: '426460791792',
    projectId: 'login-8ad4b',
    authDomain: 'login-8ad4b.firebaseapp.com',
    storageBucket: 'login-8ad4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6OQ6b1DVxTgey7CUsYWsu-1a-3GwKawY',
    appId: '1:426460791792:android:fbdc6dd1b5d63ae1651335',
    messagingSenderId: '426460791792',
    projectId: 'login-8ad4b',
    storageBucket: 'login-8ad4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmNspdSkTG2S5lGJquWOUIEGa5DOUCRuI',
    appId: '1:426460791792:ios:fc885acbdee2abc7651335',
    messagingSenderId: '426460791792',
    projectId: 'login-8ad4b',
    storageBucket: 'login-8ad4b.firebasestorage.app',
    androidClientId: '426460791792-bej0vthq9eov28a464tge30tukn2mmhk.apps.googleusercontent.com',
    iosClientId: '426460791792-kqbksalicm324srgj14b0m235uokqph7.apps.googleusercontent.com',
    iosBundleId: 'com.example.blockDioUse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmNspdSkTG2S5lGJquWOUIEGa5DOUCRuI',
    appId: '1:426460791792:ios:fc885acbdee2abc7651335',
    messagingSenderId: '426460791792',
    projectId: 'login-8ad4b',
    storageBucket: 'login-8ad4b.firebasestorage.app',
    androidClientId: '426460791792-bej0vthq9eov28a464tge30tukn2mmhk.apps.googleusercontent.com',
    iosClientId: '426460791792-kqbksalicm324srgj14b0m235uokqph7.apps.googleusercontent.com',
    iosBundleId: 'com.example.blockDioUse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZaPj8Vdp1oS_ofEgO8coqjL-DHs4YZZM',
    appId: '1:426460791792:web:e6a1c8343064a464651335',
    messagingSenderId: '426460791792',
    projectId: 'login-8ad4b',
    authDomain: 'login-8ad4b.firebaseapp.com',
    storageBucket: 'login-8ad4b.firebasestorage.app',
  );
}
